travis:
  secure:
    BINSTAR_TOKEN: aEY5vWrehQ5IVCpO2Tvd/1ocS6NlAXFG/lgPQhBV+mdCIHuiYPS0hq/jgJFYvAJe+JKXdS1II6t/q/iOm8KpT/PK/sR998o8OVYYRMGFJrfQFnAWiZJ8PG2/yPSe14jZgqOGnJWW5jWsidV+5ZDccZJ/5qFspEEMLKT+yW6EGES9RZpyz9twl7O2afo1dpipabq/pzQOv5JM/EGaQsOs8ARBrNnNOQ/O5vkdBiGPBl+Lg//jgLXDBJJsPwuWoYP6x8vhBKzvssIQuZy0A1xzSCnQASSHMjN6jXBvcTIYOeC7LysZB4ZpNS2J+D1UE6Tz+jToopi53PYcphTiTHorWNjHGbYiOQpcoqFkSc3qmk55rcEl9VuoQpNXxIdBi3zwpw1QLPHwtCrGlTY/zM28lwCZBU4i/2dw34iQQshUVN4rbPOX6O8A9YV0aR5RZ0SLys0iKia2TOsLWtQtO6ezREHvZG8hP2HIJ9kHdSWPkdkw7cwCfKk6aVZVfUitbcgucfKaLs25VKmAKMEMULAxE3M+vpYCZYuG1rhcrGQZAsW230pYlm9jt+8nK3koJT93mQdHpUK40CydswxQ9511zY9C7vn60MPpFeFzwpbnnoZ+LG4E/miG7x1eaSF7XiXK5pwMCJ5nLOxw82jefB668flIYjW+5CKKxVLHPDI2Mj0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
